In [14]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("Iris.csv")

In [51]:
X = pd.DataFrame(df.iloc[:,1:-1])
y_text = pd.DataFrame(df.iloc[:,-1])

In [61]:
# from sklearn import preprocessing

# le = preprocessing.LabelEncoder()

# # y_target = pd.DataFrame(y_text["Species"])
# y_target = np.transpose(y_text)
# y_target
# y_enc = le.fit_transform(y_target)

In [90]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

y_enc = le.fit_transform(y_text.iloc[:,0])

y = pd.DataFrame(y_enc)

print(le.classes_)

y.head(150)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


,0
0,0
1,0
2,0
3,0
4,0
...,...
145,2
146,2
147,2
148,2


In [115]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn import svm

clf = svm.SVC(kernel="linear")
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

from sklearn import metrics
confusion_mat = metrics.confusion_matrix(y_pred, y_test)

print("Confusion matrix")
print(confusion_mat)

print("Accuracy =", metrics.accuracy_score(y_test, y_pred))
print("F1 score =", metrics.f1_score(y_test, y_pred, average="macro"))

Confusion matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy = 1.0
F1 score = 1.0


c:\Users\LENOVO\anaconda3\envs\mdm\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
